name: Process Translations and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - raw/**
      - main.py

permissions:
  pages: write
  id-token: write

jobs:
  process_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Если есть зависимости, разкомментируйте:
          # pip install -r requirements.txt

      - name: Process translations
        run: |
          for version in $(ls raw); do
            # Android
            android_input="raw/$version/android_translation.txt"
            android_output="translation/$version/ad/res_release"
            if [ -f $android_input ]; then
              mkdir -p $android_output
              python main.py $android_input $android_output ad
            fi

            # iOS
            ios_input="raw/$version/ios_translation.txt"
            ios_output="translation/$version/ios/res_release"
            if [ -f $ios_input ]; then
              mkdir -p $ios_output
              python main.py $ios_input $ios_output ios
            fi
          done

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: translation

  deploy:
    needs: process_and_deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
